from gettext import gettext as _

# Table mapping codes or names to eBird codes.
#
# The integer codes come from the dropdown menu on the checklist submit
# page on the eBird web site. The 1-2 character codes are from the same
# dropdown menu on the eBird web site, but for locations in the Americas.
#
# Note: the set of codes for feeding where the variations, FR, FS, FY,
# appear to have been merged into a general code, FY (with a longer
# description). Codes for singing are likely similar.

BREEDING_CODES = {
    "0": "FO",
    "F": "F0",
    "Fly-over": "FO",
    "Fly-over (Observed)": "FO",
    "1": "OS",
    "H": "OS",
    "In Appropriate Habitat": "OS",
    "Species observed in breeding season in possible nesting habitat": "OS",
    "2": "S1",
    "S": "S1",
    "Singing Bird": "S1",
    "Singing bird(s) present (or breeding calls heard)": "S1",
    "S7": "S7",
    "Singing Bird Present 7+ days": "S7",
    "M": "SM",
    "Multiple (7+) Singing Birds": "SM",
    "3": "PO",
    "P": "PO",
    "Pair in Suitable Habitat": "PO",
    "Pair observed in suitable nesting habitat": "PO",
    "4": "T7",
    "T": "T7",
    "Territorial Defense": "T7",
    "Registration of territorial behaviour on at least two different days a week apart at same place": "T7",
    "5": "CC",
    "C": "CC",
    "Courtship, Display, or Copulation": "CC",
    "Courtship and display": "CC",
    "6": "VS",
    "N": "VS",
    "Visiting Probable Nest Site": "VS",
    "Visiting probable nest-site": "VS",
    "7": "AB",
    "A": "AB",
    "Agitated Behavior": "AB",
    "Agitated behaviour or anxiety calls from adults": "AB",
    "B": "DN",
    "Woodpecker/Wren Nest Building": "DN",
    "8": "BP",
    "PE": "BP",
    "Physiological Evidence": "BP",
    "Brood patch on adult examined in the hand": "BP",
    "9": "NB",
    "NB": "NB",
    "Nest Building": "NB",
    "Nest-building or excavating of nest-hole": "NB",
    "10": "DD",
    "DD": "DD",
    "Distraction Display": "DD",
    "Distraction-display or injury-feigning": "DD",
    "CN": "CM",
    "Carrying Nesting Material": "CM",
    "11": "UN",
    "UN": "UN",
    "Used Nest (enter 0 if no birds seen)": "UN",
    "Used nest or eggshells found": "UN",
    "12": "FL",
    "FL": "FL",
    "Recently Fledged Young": "FL",
    "Recently fledged young": "FL",
    "13": "ON",
    "ON": "ON",
    "Occupied Nest": "ON",
    "Occupied nest": "ON",
    "CF": "FY",
    "Carrying Food": "FY",
    "14": "FY",
    "Adult carrying a faecal sac or food for young": "FY",
    "FS": "FS",
    "Carrying Fecal Sac": "FS",
    "FY": "FR",
    "Feeding Young": "FR",
    "15": "NE",
    "NE": "NE",
    "Nest with Eggs": "NE",
    "Nests containing eggs": "NE",
    "16": "NY",
    "NY": "NY",
    "Nest with Young": "NY",
    "Nests with young seen or heard": "NY",
}


BREEDING_NAMES = {
    "FO": _("Fly-over"),
    "OS": _("Species observed in breeding season in possible nesting habitat"),
    "S1": _("Singing bird(s) present (or breeding calls heard)"),
    "PO": _("Pair observed in suitable nesting habitat"),
    "T7": _("Registration of territorial behaviour on at least two different days a week apart at same place"),
    "CC": _("Courtship and display"),
    "VS": _("Visiting probable nest-site"),
    "AB": _("Agitated behaviour or anxiety calls from adults"),
    "BP": _("Brood patch on adult examined in the hand"),
    "NB": _("Nest-building or excavating of nest-hole"),
    "DD": _("Distraction-display or injury-feigning"),
    "UN": _("Used nest or eggshells found"),
    "FL": _("Recently fledged young"),
    "ON": _("Occupied nest"),
    "FY": _("Adult carrying a faecal sac or food for young"),
    "NE": _("Nests containing eggs"),
    "NY": _("Nests with young seen or heard"),
}
