from gettext import gettext as _

# The names of all the protocols from Appendices 2 and 3 of the
# eBird Basic Dataset Metadata V1.14 description.

# Table mapping the English language names of a protocol to a code.
PROTOCOL_CODES = {
    "Incidental": "P20",
    "Stationary": "P21",
    "Travelling": "P22",
    "Area": "P23",
    "Trail Tracker": "P30",
    "Banding": "P33",
    "Waterbird Count": "P34",
    "My Yard Counts": "P35",
    "LoonWatch": "P39",
    "Standardized Yard Count": "P40",
    "Rusty Blackbird Spring Migration Blitz": "P41",
    "Yellow-billed Magpie Survey - General Observations": "P44",
    "Yellow-billed Magpie Survey - Traveling Count": "P45",
    "CWC Point Count": "P46",
    "CWC Area Search": "P47",
    "Random": "P48",
    "Coastal Shorebird Survey": "P49",
    "Caribbean Martin Survey": "P50",
    "Greater Gulf Refuge Waterbird Count": "P51",
    "Oiled Birds": "P52",
    "Nocturnal Flight Call Count": "P54",
    "Heron Stationary Count": "P55",
    "Heron Area Count": "P56",
    "Great Texas Birding Classic": "P57",
    "Audubon Coastal Bird Survey": "P58",
    "TNC California Waterbird Count": "P59",
    "Pelagic": "P60",
    "IBA Canada": "P61",
    "Historical": "P62",
    "Traveling - Property Specific": "P64",
    "Breeding Bird Atlas": "P65",
    "Birds 'n' Bogs Survey": "P66",
    "Common Bird Survey": "P67",
    "RAM--Iberian Seawatch Network": "P68",
    "California Brown Pelican Survey": "P69",
    "BirdLife Australia 20min-2ha survey": "P70",
    "BirdLife Australia 500m radius search": "P71",
    "BirdLife Australia 5 km radius search": "P72",
    "PROALAS Point Count (2 Bands)": "P73",
    "International Shorebird Survey": "P74",
    "Tricolored Blackbird Winter Survey": "P75",
    "CWC Travelling Count": "P80",
    "PROALAS Mini-transect": "P81",
    "PROALAS Point Count (3 Bands)": "P82",
    "Orange-breasted Falcon Site Survey": "P83",
    "Migratory Shorebird Protocol": "P84",
}

# Table mapping the protocol code to a translate name.
PROTOCOL_NAMES = {
    "P20": _("Incidental"),
    "P21": _("Stationary"),
    "P22": _("Travelling"),
    "P23": _("Area"),
    "P30": _("Trail Tracker"),
    "P33": _("Banding"),
    "P34": _("Waterbird Count"),
    "P35": _("My Yard Counts"),
    "P39": _("LoonWatch"),
    "P40": _("Standardized Yard Count"),
    "P41": _("Rusty Blackbird Spring Migration Blitz"),
    "P44": _("Yellow-billed Magpie Survey - General Observations"),
    "P45": _("Yellow-billed Magpie Survey - Traveling Count"),
    "P46": _("CWC Point Count"),
    "P47": _("CWC Area Search"),
    "P48": _("Random"),
    "P49": _("Coastal Shorebird Survey"),
    "P50": _("Caribbean Martin Survey"),
    "P51": _("Greater Gulf Refuge Waterbird Count"),
    "P52": _("Oiled Birds"),
    "P54": _("Nocturnal Flight Call Count"),
    "P55": _("Heron Stationary Count"),
    "P56": _("Heron Area Count"),
    "P57": _("Great Texas Birding Classic"),
    "P58": _("Audubon Coastal Bird Survey"),
    "P59": _("TNC California Waterbird Count"),
    "P60": _("Pelagic"),
    "P61": _("IBA Canada"),
    "P62": _("Historical"),
    "P64": _("Traveling - Property Specific"),
    "P65": _("Breeding Bird Atlas"),
    "P66": _("Birds 'n' Bogs Survey"),
    "P67": _("Common Bird Survey"),
    "P68": _("RAM--Iberian Seawatch Network"),
    "P69": _("California Brown Pelican Survey"),
    "P70": _("BirdLife Australia 20min-2ha survey"),
    "P71": _("BirdLife Australia 500m radius search"),
    "P72": _("BirdLife Australia 5 km radius search"),
    "P73": _("PROALAS Point Count (2 Bands)"),
    "P74": _("International Shorebird Survey"),
    "P75": _("Tricolored Blackbird Winter Survey"),
    "P80": _("CWC Travelling Count"),
    "P81": _("PROALAS Mini-transect"),
    "P82": _("PROALAS Point Count (3 Bands)"),
    "P83": _("Orange-breasted Falcon Site Survey"),
    "P84": _("Migratory Shorebird Protocol"),
}
